### ISSUE TITLE
error "Makefile:16: recipe for target 'data-official/2011-09.convos.txt' failed"

### ISSUE THREAD

**Issue by ypruan** [DSTC-MSR-NLP/DSTC7-End-to-End-Conversation-Modeling#2]
when I ran the "make -j4", the following error rised:
`Makefile:16: recipe for target 'data-official/2011-09.convos.txt' failed
make: *** [data-official/2011-09.convos.txt] Hangup
Makefile:16: recipe for target 'data-official/2011-10.convos.txt' failed
make: *** [data-official/2011-10.convos.txt] Hangup
Makefile:16: recipe for target 'data-official/2011-11.convos.txt' failed
make: *** [data-official/2011-11.convos.txt] Hangup
Makefile:16: recipe for target 'data-official/2011-12.convos.txt' failed
make: *** [data-official/2011-12.convos.txt] Hangup`
then the crawling process exit. Is this due to the unstable internet connection?

**Comment by Jiaxu-Zhao** [comment]
Hi, did you solved this problem? Could you share how you solve that? Thank you!
