### ISSUE TITLE
ERROR 404: Not Found 

### ISSUE THREAD

**Issue by zeunie** [DSTC-MSR-NLP/DSTC7-End-to-End-Conversation-Modeling#8]
Hi, 
I am currently collecting the DSTC7 training dataset.
However, there is a problem in DSTC7 collecting code so that I cannot collect 2015~2016 data with the instructions according to the DSTC7 website. 
I think it is because the filename extensions, which were .bz2, have been modified to .zst in 2019.
![file link](https://user-images.githubusercontent.com/54271228/125486655-307469d9-7ecb-4f7a-869a-322e529425f2.JPG)
[RS_2015-01 error log.txt](https://github.com/mgalley/DSTC7-End-to-End-Conversation-Modeling/files/6810345/RS_2015-01.error.log.txt)
It would be appreciated if you could tell me how to collect those files into my dataset. 
Thank you. 

Best regards,
Jieun Han

**Comment by Jiaxu-Zhao** [comment]
Hi, did you solved this problem? Could you share how you solve that? Thank you!

**Comment by zeunie** [comment]
Nope.. so I just collected them excluding those 2015~2016 data

**Comment by Jiaxu-Zhao** [comment]
> 

alright, thank you.
